// <auto-generated />
namespace UpFit__main.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Aliments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aliments));
        
        string IMigrationMetadata.Id
        {
            get { return "202305231314339_Aliments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
